# This document describes the configurations for the different streams that will
# be displayed on the driver station. It is used both by the Raspberry Pis for
# configuring their streams as well as the Silly Dashboard for connecting to the
# streams.

# For information on ports, see R64 and R65

- name: Vision # This one is currently not used
  ip: '127.0.0.1'
  params:
    width: 640
    height: 480
  ports:
    control: 5800 # Port used to start/stop stream, set camera params on the fly
    stream: 5805 # Port that the driver station receives video on
  logging:
    version: 1
    formatters: &formatters
      simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
      console: &consolehandler
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: /var/log/streaming-vision.log
        mode: a
    root: &rootconfig
      level: DEBUG
      handlers: [console, file]

- name: Driver
  ip: '10.10.72.11'
  params:
    awb: yes
    expmode: 1
    width: 1296
    height: 972
  ports:
    control: 5801
    stream: 5806
  logging:
    version: 1
    formatters: *formatters
    handlers:
      console: *consolehandler
      file:
        class: logging.FileHandler
        formatter: simple
        filename: /var/log/streaming-driver.log
        mode: a
    root: *rootconfig

- name: Gear
  ip: '10.10.72.11'
  params:
    awb: yes
    expmode: 1
    width: 640
    height: 480
    framerate: 5
  ports:
    control: 5802
    stream: 5807
  logging:
    version: 1
    formatters: *formatters
    handlers:
      console: *consolehandler
      file:
        class: logging.FileHandler
        formatter: simple
        filename: /var/log/streaming-gear.log
        mode: a
    root: *rootconfig
